name: BuildAndTest

on:
  push:
    branches:
      - main

jobs:
 StaticAnalysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: SwiftLint
    #   uses: norio-nomura/action-swiftlint@3.2.1

 BuildAndTest:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Build And Test
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: YVLearning.xcodeproj
          scheme: YVLearning
          destination: 'platform=iOS Simulator,name=iPhone 16'
          action: test
