name: BuildAndTest

on:
  push:
    branches:
      - main

jobs:
 StaticAnalysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    # - name: SwiftLint
    #   uses: norio-nomura/action-swiftlint@3.2.1

 BuildAndTest:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      # - name: Information
      #   run: |
      #     echo "Mac OS Version"
      #     sw_vers -productVersion
      #     printf "\nXcode Version"
      #     xcodebuild -version
      #     printf "\nSDKs"
      #     xcodebuild -showsdks
      #     printf "\nRuntimes and iOS Simulators"
      #     xcrun simctl list runtimes devices iOS
      #     printf "\n Download Platform"
      #     xcodebuild -downloadPlatform iOS

      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
          project: YVLearning.xcodeproj
          scheme: YVLearning
          destination: 'platform=iOS Simulator,name=iPhone 16'
          action: test
